
//----------------------------------------------------
// The following code was generated by C# CUP v0.1
// 11/21/2012 5:04:01 PM
//----------------------------------------------------

namespace TinyCompiler.parser
 {

/** CUP generated class containing symbol constants. */
public class TokenDef {
  /* terminals */
  public const int REPITA = 19;
  public const int EOF = 0;
  public const int MENOR = 8;
  public const int HASTA = 20;
  public const int FIN = 18;
  public const int ASIGNACION = 12;
  public const int IGUAL = 9;
  public const int SUMA = 2;
  public const int SI = 15;
  public const int PUNTO_Y_COMA = 6;
  public const int DIVISION = 4;
  public const int error = 1;
  public const int ENTONCES = 16;
  public const int RESTA = 3;
  public const int SINO = 17;
  public const int COMA = 7;
  public const int MULTIPLICACION = 5;
  public const int IDENTIFICADOR = 14;
  public const int LIT_ENTERO = 13;
  public const int PARENT_DER = 11;
  public const int ERROR = 21;
  public const int PARENT_IZQ = 10;
	}
}
